import "~/styles/globals.css";
import { GeistSans } from "geist/font/sans";
import { TRPCReactProvider } from "~/trpc/react";
import SessionWrapper from "./SessionWrapper"; // Import the SessionWrapper

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <SessionWrapper>
          {" "}
          {/* Wrap children with SessionWrapper */}
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}
